# Generated by Django 4.2.3 on 2023-08-14 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=15, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True)),
                ('link_precedence', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(editable=False, null=True)),
                ('primary_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
            ],
            options={
                'unique_together': {('phone_number', 'email')},
            },
        ),
    ]
